[package]
name = "sigma-enum-macros"
version = "0.1.0"
edition = "2024"
license = "MIT/Apache-2.0"
description = "A macro to simulate sigma types with enums."
readme = "README.md"
categories = ["data-structures", "rust-patterns"]
keywords = ["derive", "dependent-types"]

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
proc-macro2 = "1.0.103"
quote = "1.0"
syn = { version = "2.0", features = ["proc-macro", "parsing", "full"] }
