[package]
name = "sigma-enum"
version = "0.1.1"
edition = "2024"
license = "MIT/Apache-2.0"
authors = ["Milo Jacquet"]
description = "A macro to simulate sigma types with enums."
repository = "https://github.com/milojacquet/sigma-enum"
readme = "README.md"
categories = ["data-structures", "rust-patterns"]
keywords = ["derive", "dependent-types"]

[dependencies]
sigma-enum-macros = { version = "0.1.0", path = "../sigma-enum-macros" }

[dev-dependencies]
trybuild = "1.0"
